genre/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index.as_view(), name='index'),
    path('<pk>/', views.details.as_view(), name='details'),
    # path('register/', views.UserFormView.as_view(), name='userform'),
]

simplilearn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("genre.urls")),
    path('admin/', admin.site.urls),
]

genre/models.py
from django.db import models


class Collection(models.Model):
    Collection_name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    collcover = models.CharField(max_length=1000)

    def __str__(self):
        return self.Collection_name


class Piece(models.Model):
    Collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    typ = models.CharField(max_length=200)
    artist = models.CharField(max_length=50)
    year = models.IntegerField()
    piececover = models.CharField(max_length=1000)

    def __str__(self):
        return self.title

genre/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

genre/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Collection, Piece
from django.views import generic
from .forms import UserForm
from django.contrib.auth import authenticate, login
from django.views.generic import View


class index(generic.ListView):
    template_name = 'genre/genretemplate.html'

    def get_queryset(self):
        return Collection.objects.all()


class details(generic.DetailView):
    model = Collection
    template_name = 'genre/detailtemplate.html'


"""class UserFormView(View):
    from_class = UserForm
    template_name = 'genre/template.html'


    def get(self, request):
        from=self.from_class(None)
        return render(request, self.template_name,{'form': forms})


    def post(self, request):
        form=self.from_class(request.post)


        if form.is_valid():
             user=form.save()
             username=form.cleaned_data('username')
             password=form.cleaned_data('password')
             user.set_password(password)
             user.save()


             newuser=authenticate(username=username, password=password)

             if newuser is not None:
                 if newuser.is_active:
                     login(request,newuser)
                     return redirect("/index")

        return render(request, self.template_name, {'form': form})"""

genre/templates/genre/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Base</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href=" ">Home</a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li class="active">
          <a href="/genre/register">register</a>
      </li>
      <li class="">
          <a>{{request.user}}</a>
      </li>
    </ul>
  </div>
</nav>

{% block content %}
{% endblock %}

</body>
</html>

genre/templates/genre/detailtemplate.html
<!DOCTYPE html>
{% extends 'genre/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>piece</title>
{% block content %}
    <h1>You are in the second page </h1>
</head>
<body>

 {% for pieceobj in collection.piece_set.all %}
        <div align="center">
           <img src="{{pieceobj.piececover}}" height="200" width="200">
           <h2>{{pieceobj.title}}-{{pieceobj.artist}}</h2>
           <h3>{{pieceobj.typ}}</h3>
           <h3>{{pieceobj.year}}</h3>
           <br/>
        </div>
 {% endfor %}

{% endblock %}

</body>
</html>

genre/templates/genre/formtemplate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
   {% extends 'genre/base.html'%}
</head>
<body>
     {% block content %}
         <from action="" mothod="post">
             {csrf_token}
             username:
             <input type="text" name="username">
             <br/>

             Email:
             <input type="text" name="email">
             <br/>

             password:
             <input type="password" name="password">
             <br/>

             <input type="submit" value="submit">
         </from>
     {% endblock %}
</body>
</html>

genre/templates/genre/genretemplate.html
<!DOCTYPE html>
{% extends 'genre/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <h1> Hey buddy u almost there </h1>
</head>
<body>
{% block content %}
    {% for genreobj in object_list %}
        <div align="center">
           <img src="{{genreobj.collcover}}" height="200" width="200">
           <h2><a href="{{genreobj.id}}/">{{genreobj.Collection_name}}</a></h2>
           <h3>{{genreobj.description}}</h3>
           <br/>
        </div>
    {% endfor %}
{% endblock %}
</body>
</html>